export const EXCHANGE = {
  CURRENCIES: {
    BASE: {
      SET_NEW_CURRENCY: 'EXCHANGE.CURRENCIES.BASE.SET_NEW_CURRENCY',
      SET_AMOUNT: 'EXCHANGE.CURRENCIES.BASE.SET_AMOUNT',
      SET_FOCUSED: 'EXCHANGE.CURRENCIES.BASE.SET_FOCUSED'
    },
    QUOTE: {
      SET_NEW_CURRENCY: 'EXCHANGE.CURRENCIES.QUOTE.SET_NEW_CURRENCY',
      SET_AMOUNT: 'EXCHANGE.CURRENCIES.QUOTE.SET_AMOUNT',
      SET_FOCUSED: 'EXCHANGE.CURRENCIES.QUOTE.SET_FOCUSED'
    },
    SWITCH: 'EXCHANGE.CURRENCIES.SWITCH'
  },
  RATES:{
    FETCH: {
      START: 'EXCHANGE.RATES.FETCH.START',
      STOP: 'EXCHANGE.RATES.FETCH.STOP',
      SUCCESS: 'EXCHANGE.RATES.FETCH.SUCCESS',
      ERROR: 'EXCHANGE.RATES.FETCH.ERROR'
    }
  },
  TRADE: {
    REQUEST: 'EXCHANGE.TRADE.REQUEST',
    SUCCESS: 'EXCHANGE.TRADE.SUCCESS',
    ERROR: 'EXCHANGE.TRADE.ERROR'
  },
  ERROR: {
    CLEAR: 'EXCHANGE.ERROR.CLEAR'
  },
  CLEAR_STATE: 'EXCHANGE.CLEAR_STATE'
};

export const USER = {
  ACCOUNTS: {
    UPDATE: {
      REQUEST: 'USER.ACCOUNTS.UPDATE.REQUEST',
      SUCCESS: 'USER.ACCOUNTS.UPDATE.SUCCESS',
      ERROR: 'USER.ACCOUNTS.UPDATE.ERROR'
    }
  }
};
